version: 3.0.0-beta.2+{build}

platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

environment:
  GH_TOKEN:
    secure: mYjFV31UpA9DJblj4EH37NbPJ03Oci3yQAu210QeJMrlNdM/ayc8XJXnSr7wUKiR

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 5.10.0 x64
  - git reset --hard HEAD
  - npm install npm -g
  - npm install electron-builder@next
  - npm prune
  - npm install

build_script:
  - node --version
  - npm --version
  - npm run dist:win32

test: off

skip_non_tags: true
