version: 3.0.0-rc.2+{build}

platform:
  - x86
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

environment:
  GH_TOKEN:
    secure: mYjFV31UpA9DJblj4EH37NbPJ03Oci3yQAu210QeJMrlNdM/ayc8XJXnSr7wUKiR

init:
  - git config --global core.autocrlf input

install:
  - ps: $env:PLATFORM = $env:platform
  - ps: Install-Product node 6 $env:platform
  - git reset --hard HEAD
  - npm install npm -g
  - npm install electron-builder@11.3.0
  - npm prune
  - npm install

build_script:
  - node --version
  - npm --version
  - npm run dist

test: off

skip_non_tags: true
